<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>PCSMNext.App</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <ApplicationIcon>icon-light.ico</ApplicationIcon>
	<IncludeAllContentForSelfExtract>True</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="Themes\DefaultTheme.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon-light.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCSMNext.Core\PCSMNext.Core.csproj" />
    <ProjectReference Include="..\PCSMNext.Services\PCSMNext.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Themes\DefaultTheme.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Themes\Generic.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
